import { Rubik } from 'next/font/google'
import './globals.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import {AppProvider} from '../components/AppContext'


const rubik = Rubik({ subsets: ['latin'],weight: ['300','400','500','600','700'] })

export const metadata = {
  title: 'CODE3035',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <main className='max-w-6xl mx-auto px-4 bg-[#fdfdfd]'>
     <AppProvider>
        <Header/>
        {children}
        <Footer/>
     </AppProvider>
        </main>
        </body>
    </html>
  )
}
